version: "3.8"

services:
  postgres:
    container_name: postgres-metabase
    image: postgres:14-alpine
    restart: always
    env_file:
      - ./config/postgres/postgres.env
    volumes:
      - metabase-db-data:/var/lib/postgresql/data/metabase
      - ./config/postgres/:/docker-entrypoint-initdb.d/
    ports:
      - 5432:5432

  metabase:
    container_name: metabase
    image: metabase/metabase
    restart: always
    ports:
      - 3000:3000/tcp
    volumes:
      - metabase-data:/metabase-data
    env_file:
      - ./config/metabase/metabase.env
    depends_on:
      - postgres
    links:
      - postgres:postgres

  nginx:
    container_name: nginx-metabase
    image: nginx:latest
    volumes:
      # - ./config/nginx:/etc/nginx/conf.d # conflict in production
      - ./config/nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
      - 443:443
    depends_on:
      - metabase
    restart: always
    links:
      - metabase:metabase

volumes:
  metabase-db-data:
  metabase-data:
